version: 2.0
env_vars: &env_vars
  environment:
    - APP_NAME: plone-gatsby-blog

jobs:
  build_deploy:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - $PROJ_FINGERPRINT

      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Compile gatsbyjs site
          command: npm run build

      - run:
          name: Install and configure dependencies for gh-pages
          command: |
            sudo npm install -g --silent gh-pages@2.0.1
            git config user.email "dadlobr@gmail.com"
            git config user.name "Dadlo"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --message "[skip ci] Updates" --dist ./public

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_deploy:
          filters:
            branches:
              only: master
